#! /bin/sh

I3CACHE=$HOME/.cache/i3

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

if xrandr | grep "HDMI-A-0 connected"; then
	xrandr --output HDMI-A-0 --primary --left-of eDP
	
	# my external monitor switches between connected/disconnected
	# when in standby mode. this triggers my HDMI hotplug udev
	# script and prevents the laptop from ever going to sleep
	# so I just turn it off and stick to locking the screen
	xset -dpms
fi

mkdir -p "$I3CACHE"
exec i3 >> "$I3CACHE/stdout" 2>> "$I3CACHE/stderr"

